# Generated by Django 4.1.7 on 2023-05-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='userbase'),
        ),
    ]
