# Generated by Django 4.1.7 on 2023-05-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_userbase_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='login',
            new_name='usertag',
        ),
    ]
