# Generated by Django 4.1.7 on 2023-05-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_login_userbase_usertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='company',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
