# Generated by Django 4.1.7 on 2023-05-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_article_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.CharField(default='Это превью статьи к сожалению не было описано.', max_length=500),
        ),
    ]
