# Generated by Django 4.1.7 on 2023-05-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_imagesnews_options_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesnews',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='news_images'),
        ),
    ]
