# Generated by Django 4.1.7 on 2023-05-25 16:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_likesnews_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comments', models.CharField(max_length=400)),
                ('date_create', models.DateTimeField(default=datetime.datetime.now)),
                ('commentator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.news')),
            ],
            options={
                'verbose_name_plural': 'CommentsNews',
            },
        ),
    ]
